- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2
    - postgresql-9.3

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf

- name: Restart PostgreSQL
  command: service postgresql restart

- name: create the postgresql user for application
  postgresql_user: name=deploy
  sudo: yes
  sudo_user: postgres

- name: create the postgresql database for application
  postgresql_db: name=app_{{item}} owner=deploy state=present
  sudo: yes
  sudo_user: postgres
  with_items:
    - apps
