- name: Make the sudo group
  group: name=sudo system=yes state=present

- name: Make the deploy group
  group: name=deploy system=yes state=present

- name: Create users
  user: name={{ item.name }} comment="{{ item.fullname }}" groups={{ item.groups }} shell=/bin/bash
  with_items: users

- name: Add SSH keys
  authorized_key: user={{ item.name }} key="{{ lookup('file', 'keys/' + item.name) }}"
  with_items: users

- name: Add SSH key for root
  authorized_key: user=root key="{{ lookup('file', 'keys/root') }}"

