- name: Add puma-manager
  template: src=puma-manager.j2 dest=/etc/init/puma-manager.conf force=yes mode=755
  tags: puma

- name: Add puma config
  template: src=etc_puma.conf.j2 dest=/etc/puma.conf force=yes mode=755
  tags: puma

- name: Add puma init script
  template: src=etc_init_puma.j2 dest=/etc/init/puma.conf force=yes mode=755
  tags: puma

- name: Add puma shared/config
  template: src=puma_production.j2 dest=/data/{{item}}/shared/config/puma/production.rb force=yes mode=755
  tags: puma
  with_items:
    - apps

- name: Make shared/tmp/sockets
  file: path=/data/{{item}}/shared/tmp/sockets group=deploy owner=deploy state=directory
  tags: tmp
  with_items:
    - apps

- name: Restart puma-manager
  action: service name=puma-manager state=restarted